version: '3'

services:
  apache2:
    build: apache2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/ftp:/srv/ftp:ro
      - letsencrypt:/etc/letsencrypt:ro

  vsftpd:
    build: vsftpd
    restart: unless-stopped
    volumes:
      - /srv/ftp:/srv/ftp
    network_mode: host

  pptp:
    build: pptp
    restart: unless-stopped
    ports:
      - "1723:1723"
    privileged: true

  l2tp:
    image: hwdsl2/ipsec-vpn-server
    restart: unless-stopped
    env_file:
      - l2tp/vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true

  openvpn:
    build: openvpn
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    privileged: true

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - mysql/password.env
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_HOST: mysql

  cgserver:
    build: cgserver
    depends_on:
      - mysql
    restart: unless-stopped

  letsencrypt:
    build: letsencrypt
    depends_on:
      - apache2
    env_file:
      - letsencrypt/sites.env
    volumes:
      - /srv/ftp:/srv/ftp
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:

  ftp:
