FROM cscg/base

RUN apt-get update && \
	apt-get install --no-install-recommends -y openvpn iptables dnsutils && \
	rm -rf /var/lib/apt/lists/*

RUN pip install requests && \
	rm -r ~/.cache/pip

COPY conf /etc/openvpn/cscg/conf
COPY entrypoint.sh /entrypoint.sh

WORKDIR /etc/openvpn/cscg/conf

RUN mkdir ../log
RUN sed -i 's/^proto udp/proto tcp/g' server.conf

EXPOSE 1194
ENTRYPOINT ["/entrypoint.sh"]
CMD ["openvpn", "server.conf"]
